/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/upand0wn/open-powershell-here
Do not edit this file directly.
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  NOTICE_NOT_FOUND_LINUX: () => NOTICE_NOT_FOUND_LINUX,
  NOTICE_NOT_FOUND_MACOS: () => NOTICE_NOT_FOUND_MACOS,
  NOTICE_NOT_FOUND_WINDOWS: () => NOTICE_NOT_FOUND_WINDOWS,
  NOTICE_NO_VAULT_PATH: () => NOTICE_NO_VAULT_PATH,
  NOTICE_SEMICOLON: () => NOTICE_SEMICOLON,
  NOTICE_START_FAILED: () => NOTICE_START_FAILED,
  NOTICE_UNSUPPORTED_PLATFORM: () => NOTICE_UNSUPPORTED_PLATFORM,
  default: () => VaultTerminalPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/vault-path.ts
var import_obsidian = require("obsidian");
function getLocalAdapter(vault) {
  if (vault === null || vault === void 0) {
    return null;
  }
  const adapter = vault.adapter;
  return adapter instanceof import_obsidian.FileSystemAdapter ? adapter : null;
}
function getVaultRootPath(vault) {
  const adapter = getLocalAdapter(vault);
  if (adapter === null) {
    return null;
  }
  return adapter.getBasePath();
}
function getFolderPath(vault, folder) {
  if (folder === null || folder === void 0 || !(folder instanceof import_obsidian.TFolder)) {
    return null;
  }
  const adapter = getLocalAdapter(vault);
  if (adapter === null) {
    return null;
  }
  const normalized = folder.path.replace(/^\/+|\/+$/g, "");
  if (normalized === "") {
    return adapter.getBasePath();
  }
  return adapter.getFullPath(normalized);
}
function getTargetPath(vault, target) {
  if (target === null || target === void 0) {
    return null;
  }
  if (target instanceof import_obsidian.TFolder) {
    return getFolderPath(vault, target);
  }
  if (target instanceof import_obsidian.TFile) {
    if (target.parent instanceof import_obsidian.TFolder) {
      return getFolderPath(vault, target.parent);
    }
    const adapter = getLocalAdapter(vault);
    if (adapter === null) {
      return null;
    }
    const lastSlash = target.path.lastIndexOf("/");
    if (lastSlash === -1) {
      return adapter.getBasePath();
    }
    const parentDir = target.path.substring(0, lastSlash).replace(/^\/+|\/+$/g, "");
    if (parentDir === "") {
      return adapter.getBasePath();
    }
    return adapter.getFullPath(parentDir);
  }
  return null;
}

// src/terminals/windows/candidates.ts
var import_node_path = require("node:path");
var PATH_CANDIDATE = "pwsh.exe";
var PROGRAM_FILES_RELATIVE = ["PowerShell", "7", "pwsh.exe"];
var DOTNET_TOOLS_RELATIVE = [".dotnet", "tools", "pwsh.exe"];
function buildCandidates(env = process.env) {
  const raw = [{ path: PATH_CANDIDATE, source: "PATH" }];
  const programFiles = env.ProgramFiles;
  if (programFiles !== void 0 && programFiles !== "") {
    raw.push({ path: import_node_path.win32.join(programFiles, ...PROGRAM_FILES_RELATIVE), source: "ProgramFiles" });
  }
  const userProfile = env.USERPROFILE;
  if (userProfile !== void 0 && userProfile !== "") {
    raw.push({
      path: import_node_path.win32.join(userProfile, ...DOTNET_TOOLS_RELATIVE),
      source: "UserProfileDotnetTools"
    });
  }
  return dedupeCandidates(raw);
}
function dedupeCandidates(candidates) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const candidate of candidates) {
    const key = candidate.path.toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    out.push(candidate);
  }
  return out;
}

// src/terminals/windows/version-probe.ts
var import_node_child_process = require("node:child_process");

// src/terminals/windows/types.ts
var PROBE_ARGS = [
  "-NoLogo",
  "-NoProfile",
  "-NonInteractive",
  "-Command",
  "$PSVersionTable.PSVersion.Major"
];
var PROBE_TIMEOUT_MS = 5e3;

// src/terminals/windows/version-probe.ts
function runExecFile(file, args, options) {
  return new Promise((resolve, reject) => {
    (0, import_node_child_process.execFile)(file, args, options, (error, stdout, _stderr) => {
      if (error !== null) {
        reject(error instanceof Error ? error : new Error(String(error)));
        return;
      }
      const text = typeof stdout === "string" ? stdout : stdout.toString("utf8");
      resolve({ stdout: text });
    });
  });
}
async function probeMajorVersion(exePath, options = {}) {
  var _a;
  try {
    const { stdout } = await runExecFile(exePath, [...PROBE_ARGS], {
      shell: false,
      windowsHide: true,
      timeout: (_a = options.timeoutMs) != null ? _a : PROBE_TIMEOUT_MS,
      encoding: "utf8",
      env: process.env
    });
    return parseMajorVersion(stdout);
  } catch (e) {
    return null;
  }
}
function parseMajorVersion(rawOutput) {
  const trimmed = rawOutput.trim();
  if (!/^[0-9]+$/.test(trimmed)) {
    return null;
  }
  const major = Number.parseInt(trimmed, 10);
  if (!Number.isSafeInteger(major)) {
    return null;
  }
  return major >= 7 ? major : null;
}

// src/terminals/windows/finder.ts
var PowerShellFinder = class {
  constructor(deps) {
    this.verified = null;
    this.resolving = null;
    var _a, _b, _c;
    this.deps = {
      buildCandidates: (_a = deps == null ? void 0 : deps.buildCandidates) != null ? _a : buildCandidates,
      probeMajorVersion: (_b = deps == null ? void 0 : deps.probeMajorVersion) != null ? _b : probeMajorVersion,
      env: deps == null ? void 0 : deps.env,
      debug: (_c = deps == null ? void 0 : deps.debug) != null ? _c : ((msg) => console.debug(`[Native Terminal Here] ${msg}`))
    };
  }
  get cached() {
    if (this.verified === null) {
      return null;
    }
    return {
      id: "powershell",
      displayName: "PowerShell",
      binaryPath: this.verified.path,
      extra: { majorVersion: this.verified.majorVersion }
    };
  }
  get verifiedPowerShell() {
    return this.verified;
  }
  resolve() {
    if (this.verified !== null) {
      return Promise.resolve(this.cached);
    }
    if (this.resolving !== null) {
      return this.resolving;
    }
    this.resolving = this.findBest().finally(() => {
      this.resolving = null;
    });
    return this.resolving;
  }
  invalidate() {
    this.verified = null;
  }
  async findBest() {
    var _a, _b, _c, _d;
    const candidates = this.deps.buildCandidates(this.deps.env);
    for (const candidate of candidates) {
      const major = await this.deps.probeMajorVersion(candidate.path);
      if (major !== null) {
        this.verified = { path: candidate.path, majorVersion: major };
        (_b = (_a = this.deps).debug) == null ? void 0 : _b.call(_a, `verified pwsh: ${candidate.path} (major ${major})`);
        return this.cached;
      }
      (_d = (_c = this.deps).debug) == null ? void 0 : _d.call(_c, `rejected candidate ${candidate.source}: ${candidate.path}`);
    }
    return null;
  }
};

// src/terminals/windows/launcher.ts
var import_node_child_process2 = require("node:child_process");
var WINDOWS_TERMINAL = "wt.exe";
function spawnDirect(verified, targetDir) {
  return spawnPwsh(
    verified.path,
    ["-WorkingDirectory", targetDir],
    targetDir,
    "inherit"
  );
}
function spawnHosted(verified, targetDir) {
  return spawnPwsh(
    WINDOWS_TERMINAL,
    ["-w", "0", verified.path, "-WorkingDirectory", targetDir],
    targetDir,
    "ignore"
  );
}
function spawnPwsh(executable, args, targetDir, stdio) {
  return new Promise((resolve) => {
    let settled = false;
    let child;
    try {
      child = (0, import_node_child_process2.spawn)(executable, args, {
        cwd: targetDir,
        env: process.env,
        shell: false,
        windowsHide: false,
        detached: false,
        stdio
      });
    } catch (error) {
      resolve({ ok: false, code: "UNKNOWN", error });
      return;
    }
    child.once("error", (error) => {
      if (settled) {
        return;
      }
      settled = true;
      const code = error.code;
      resolve({
        ok: false,
        code: code === "ENOENT" ? "ENOENT" : "UNKNOWN",
        error
      });
    });
    child.once("spawn", () => {
      var _a;
      if (settled) {
        return;
      }
      settled = true;
      resolve({ ok: true, pid: (_a = child.pid) != null ? _a : 0 });
    });
    child.unref();
  });
}
function launchInteractive(verified, targetDir) {
  if (targetDir.includes(";")) {
    return Promise.resolve({
      ok: false,
      code: "UNKNOWN",
      error: new Error(
        "Refusing to launch PowerShell for a path containing a semicolon (;)."
      )
    });
  }
  return spawnHosted(verified, targetDir).then((outcome) => {
    if (outcome.ok) {
      return outcome;
    }
    if (outcome.code === "ENOENT") {
      return spawnDirect(verified, targetDir);
    }
    return outcome;
  });
}

// src/terminals/linux/finder.ts
var import_node_path2 = require("node:path");

// src/terminals/linux/candidates.ts
var LINUX_TERMINALS = [
  {
    id: "xdg-terminal-exec",
    displayName: "System Default (xdg-terminal-exec)",
    binary: "xdg-terminal-exec",
    // Resolves the user's configured default terminal and forwards the
    // working directory, e.g. on Ubuntu 26.04 this runs
    // `ptyxis --new-window --working-directory <dir>`.
    buildArgs: (dir) => [`--dir=${dir}`]
  },
  {
    id: "x-terminal-emulator",
    displayName: "Terminal",
    binary: "x-terminal-emulator",
    // Debian/Ubuntu alternatives link to the system default terminal. The
    // finder follows the link and, when it points at a terminal listed
    // below, launches that terminal with its own working-directory flag.
    // Otherwise the target is unknown and no flag is portable, so the
    // launcher's `cwd` is the only way the directory is conveyed.
    buildArgs: () => [],
    systemDefaultLink: true
  },
  {
    id: "alacritty",
    displayName: "Alacritty",
    binary: "alacritty",
    buildArgs: (dir) => ["--working-directory", dir]
  },
  {
    id: "foot",
    displayName: "Foot",
    binary: "foot",
    buildArgs: (dir) => ["-D", dir]
  },
  {
    id: "ghostty",
    displayName: "Ghostty",
    binary: "ghostty",
    buildArgs: (dir) => [`--working-directory=${dir}`]
  },
  {
    id: "gnome-terminal",
    displayName: "GNOME Terminal",
    binary: "gnome-terminal",
    buildArgs: (dir) => [`--working-directory=${dir}`],
    aliases: ["gnome"]
  },
  {
    id: "kgx",
    displayName: "GNOME Console",
    binary: "kgx",
    buildArgs: (dir) => [`--working-directory=${dir}`],
    aliases: ["gnome-console"]
  },
  {
    id: "kitty",
    displayName: "Kitty",
    binary: "kitty",
    buildArgs: (dir) => ["--directory", dir]
  },
  {
    id: "konsole",
    displayName: "Konsole",
    binary: "konsole",
    buildArgs: (dir) => ["--workdir", dir]
  },
  {
    id: "ptyxis",
    displayName: "Ptyxis",
    binary: "ptyxis",
    // `--new-window` is required so an already running Ptyxis instance opens
    // a new window at the target directory instead of focusing an existing
    // window and dropping the working directory.
    buildArgs: (dir) => ["--new-window", `--working-directory=${dir}`]
  },
  {
    id: "wezterm",
    displayName: "WezTerm",
    binary: "wezterm",
    buildArgs: (dir) => ["start", "--cwd", dir]
  },
  {
    id: "xfce4-terminal",
    displayName: "XFCE4 Terminal",
    binary: "xfce4-terminal",
    buildArgs: (dir) => [`--working-directory=${dir}`],
    aliases: ["xfce4"]
  }
];

// src/terminals/linux/alternatives.ts
var import_node_child_process3 = require("node:child_process");
var QUERY_TIMEOUT_MS = 5e3;
function queryAlternative(name) {
  return new Promise((resolve) => {
    try {
      (0, import_node_child_process3.execFile)(
        "update-alternatives",
        ["--query", name],
        { shell: false, timeout: QUERY_TIMEOUT_MS, encoding: "utf8", env: process.env },
        (error, stdout) => {
          resolve(error === null ? parseAlternativeValue(stdout) : null);
        }
      );
    } catch (e) {
      resolve(null);
    }
  });
}
function parseAlternativeValue(output) {
  const match = /^Value:[ \t]*(\S.*)$/m.exec(output);
  if (match === null) {
    return null;
  }
  const value = match[1].trim();
  return value === "" || value === "none" ? null : value;
}

// src/terminals/linux/finder.ts
function matchesPreferredTerminal(spec, normalizedPreferred) {
  var _a;
  if (spec.id.toLowerCase() === normalizedPreferred) {
    return true;
  }
  if (spec.binary.toLowerCase() === normalizedPreferred) {
    return true;
  }
  return ((_a = spec.aliases) != null ? _a : []).some((alias) => alias.toLowerCase() === normalizedPreferred);
}
function toTerminal(spec) {
  return { id: spec.id, displayName: spec.displayName, binaryPath: spec.binary, extra: { spec } };
}
var LinuxTerminalFinder = class {
  constructor(deps) {
    this.verified = null;
    this.currentPreferredId = null;
    this.resolving = null;
    this.rejected = /* @__PURE__ */ new Set();
    var _a, _b, _c;
    this.deps = {
      specs: (_a = deps == null ? void 0 : deps.specs) != null ? _a : LINUX_TERMINALS,
      queryAlternative: (_b = deps == null ? void 0 : deps.queryAlternative) != null ? _b : queryAlternative,
      debug: (_c = deps == null ? void 0 : deps.debug) != null ? _c : ((msg) => console.debug(`[Native Terminal Here] ${msg}`))
    };
  }
  get cached() {
    return this.verified;
  }
  setPreferredTerminal(id) {
    if (this.currentPreferredId !== id) {
      this.currentPreferredId = id;
      this.invalidate();
    }
  }
  resolve(preferredId) {
    const targetPreferred = preferredId != null ? preferredId : this.currentPreferredId;
    if (targetPreferred !== this.currentPreferredId) {
      this.currentPreferredId = targetPreferred;
      this.invalidate();
    }
    if (this.verified !== null) {
      return Promise.resolve(this.verified);
    }
    if (this.resolving !== null) {
      return this.resolving;
    }
    this.resolving = this.findBest(this.currentPreferredId).finally(() => {
      this.resolving = null;
    });
    return this.resolving;
  }
  /** `terminal` could not be started: skip it and offer the next candidate. */
  reject(terminal) {
    var _a, _b;
    this.rejected.add(terminal.id);
    this.verified = null;
    (_b = (_a = this.deps).debug) == null ? void 0 : _b.call(_a, `rejected terminal ${terminal.displayName} (${terminal.binaryPath})`);
  }
  invalidate() {
    this.verified = null;
    this.rejected.clear();
  }
  /**
   * Follow a system-default link (e.g. `x-terminal-emulator`) to the
   * terminal it points at. Returns that terminal when it is a supported
   * one, so it is launched with its own working-directory flag; otherwise
   * returns the link itself.
   */
  async followSystemDefault(link) {
    const targetPath = await this.deps.queryAlternative(link.binary);
    if (targetPath === null) {
      return link;
    }
    const target = import_node_path2.posix.basename(targetPath).replace(/\.wrapper$/, "");
    const match = this.deps.specs.find(
      (s) => s.systemDefaultLink !== true && s.binary === target && !this.rejected.has(s.id)
    );
    return match != null ? match : link;
  }
  async findBest(preferredId) {
    var _a, _b;
    const candidates = [...this.deps.specs];
    if (preferredId !== null && preferredId !== "auto" && preferredId !== "") {
      const normalizedPreferred = preferredId.toLowerCase().replace(/^terminal-choice-/, "");
      const match = this.deps.specs.find((s) => matchesPreferredTerminal(s, normalizedPreferred));
      if (match !== void 0) {
        candidates.unshift(match);
      }
    }
    const next = candidates.find((s) => !this.rejected.has(s.id));
    if (next === void 0) {
      this.rejected.clear();
      return null;
    }
    const spec = next.systemDefaultLink === true ? await this.followSystemDefault(next) : next;
    this.verified = { ...toTerminal(spec), id: next.id };
    (_b = (_a = this.deps).debug) == null ? void 0 : _b.call(_a, `trying terminal: ${spec.displayName} (${spec.binary})`);
    return this.verified;
  }
};

// src/terminals/spawn-detached.ts
var import_node_child_process4 = require("node:child_process");
function spawnDetached(executable, args, targetDir) {
  return new Promise((resolve) => {
    let settled = false;
    let child;
    try {
      child = (0, import_node_child_process4.spawn)(executable, args, {
        cwd: targetDir,
        env: process.env,
        shell: false,
        detached: true,
        stdio: "ignore"
      });
    } catch (error) {
      resolve({ ok: false, code: "UNKNOWN", error });
      return;
    }
    child.once("error", (error) => {
      if (settled) {
        return;
      }
      settled = true;
      const code = error.code;
      resolve({
        ok: false,
        code: code === "ENOENT" ? "ENOENT" : "UNKNOWN",
        error
      });
    });
    child.once("spawn", () => {
      var _a;
      if (settled) {
        return;
      }
      settled = true;
      resolve({ ok: true, pid: (_a = child.pid) != null ? _a : 0 });
    });
    child.unref();
  });
}

// src/terminals/linux/launcher.ts
function launchLinuxTerminal(terminal, targetDir) {
  var _a;
  const spec = (_a = terminal.extra) == null ? void 0 : _a.spec;
  const args = spec !== void 0 ? spec.buildArgs(targetDir) : [`--working-directory=${targetDir}`];
  return spawnDetached(terminal.binaryPath, args, targetDir);
}

// src/terminals/macos/finder.ts
var import_node_path3 = require("node:path");

// src/terminals/macos/candidates.ts
var MAC_OPEN_BINARY = "/usr/bin/open";
var MAC_APP_DIRS = [
  "/Applications",
  "/System/Applications/Utilities",
  "/System/Applications"
];
var MAC_TERMINALS = [
  {
    id: "terminal",
    displayName: "Terminal",
    appBundle: "Terminal.app",
    // Terminal.app opens a new window at a folder passed as a document.
    buildArgs: (appPath, dir) => ["-a", appPath, dir]
  },
  {
    id: "ghostty",
    displayName: "Ghostty",
    appBundle: "Ghostty.app",
    buildArgs: (appPath, dir) => ["-a", appPath, dir]
  },
  {
    id: "kitty",
    displayName: "Kitty",
    appBundle: "kitty.app",
    // `-n` is required: `--args` are dropped when kitty is already running.
    buildArgs: (appPath, dir) => ["-n", "-a", appPath, "--args", "--directory", dir]
  }
];

// src/terminals/macos/finder.ts
var MacTerminalFinder = class {
  constructor(deps) {
    this.verified = null;
    this.currentPreferredId = null;
    this.resolving = null;
    this.rejected = /* @__PURE__ */ new Set();
    var _a, _b, _c;
    this.deps = {
      specs: (_a = deps == null ? void 0 : deps.specs) != null ? _a : MAC_TERMINALS,
      appDirs: (_b = deps == null ? void 0 : deps.appDirs) != null ? _b : MAC_APP_DIRS,
      env: deps == null ? void 0 : deps.env,
      debug: (_c = deps == null ? void 0 : deps.debug) != null ? _c : ((msg) => console.debug(`[Native Terminal Here] ${msg}`))
    };
  }
  get cached() {
    return this.verified;
  }
  setPreferredTerminal(id) {
    if (this.currentPreferredId !== id) {
      this.currentPreferredId = id;
      this.invalidate();
    }
  }
  resolve() {
    if (this.verified !== null) {
      return Promise.resolve(this.verified);
    }
    if (this.resolving !== null) {
      return this.resolving;
    }
    this.resolving = Promise.resolve(this.findBest(this.currentPreferredId)).finally(() => {
      this.resolving = null;
    });
    return this.resolving;
  }
  /** `terminal` could not be opened: skip it and offer the next candidate. */
  reject(terminal) {
    var _a, _b, _c;
    const appPath = (_a = terminal.extra) == null ? void 0 : _a.appPath;
    if (typeof appPath === "string") {
      this.rejected.add(appPath);
    }
    this.verified = null;
    (_c = (_b = this.deps).debug) == null ? void 0 : _c.call(_b, `rejected terminal ${terminal.displayName} (${String(appPath)})`);
  }
  invalidate() {
    this.verified = null;
    this.rejected.clear();
  }
  searchDirs() {
    var _a;
    const home = ((_a = this.deps.env) != null ? _a : process.env).HOME;
    const dirs = [...this.deps.appDirs];
    if (home !== void 0 && home !== "") {
      dirs.push(import_node_path3.posix.join(home, "Applications"));
    }
    return dirs;
  }
  findBest(preferredId) {
    var _a, _b;
    const specs = [...this.deps.specs];
    if (preferredId !== null && preferredId !== "auto" && preferredId !== "") {
      const normalizedPreferred = preferredId.toLowerCase().replace(/^terminal-choice-/, "");
      const match = this.deps.specs.find((s) => s.id === normalizedPreferred);
      if (match !== void 0) {
        specs.unshift(match);
      }
    }
    for (const spec of specs) {
      for (const dir of this.searchDirs()) {
        const appPath = import_node_path3.posix.join(dir, spec.appBundle);
        if (!this.rejected.has(appPath)) {
          this.verified = {
            id: spec.id,
            displayName: spec.displayName,
            binaryPath: MAC_OPEN_BINARY,
            extra: { spec, appPath }
          };
          (_b = (_a = this.deps).debug) == null ? void 0 : _b.call(_a, `trying terminal: ${spec.displayName} (${appPath})`);
          return this.verified;
        }
      }
    }
    this.rejected.clear();
    return null;
  }
};

// src/terminals/macos/launcher.ts
var import_node_child_process5 = require("node:child_process");
var OPEN_TIMEOUT_MS = 1e4;
function launchMacTerminal(terminal, targetDir) {
  var _a, _b;
  const spec = (_a = terminal.extra) == null ? void 0 : _a.spec;
  const appPath = (_b = terminal.extra) == null ? void 0 : _b.appPath;
  if (spec === void 0 || appPath === void 0) {
    return Promise.resolve({
      ok: false,
      code: "UNKNOWN",
      error: new Error("Resolved macOS terminal is missing its app bundle path.")
    });
  }
  return new Promise((resolve) => {
    try {
      const child = (0, import_node_child_process5.execFile)(
        terminal.binaryPath,
        spec.buildArgs(appPath, targetDir),
        { cwd: targetDir, env: process.env, shell: false, timeout: OPEN_TIMEOUT_MS },
        (error) => {
          var _a2;
          if (error === null) {
            resolve({ ok: true, pid: (_a2 = child.pid) != null ? _a2 : 0 });
            return;
          }
          const code = error.code;
          resolve({
            ok: false,
            code: code === "ENOENT" || typeof code === "number" ? "ENOENT" : "UNKNOWN",
            error
          });
        }
      );
    } catch (error) {
      resolve({ ok: false, code: "UNKNOWN", error });
    }
  });
}

// src/terminals/manager.ts
var MAX_LAUNCH_ATTEMPTS = 32;
var TerminalManager = class {
  constructor(deps) {
    this.explicitPreferredTerminal = null;
    var _a;
    this.platform = (_a = deps == null ? void 0 : deps.platform) != null ? _a : process.platform;
    if ((deps == null ? void 0 : deps.finder) !== void 0) {
      this.finder = deps.finder;
    } else if (this.platform === "win32") {
      this.finder = new PowerShellFinder();
    } else if (this.platform === "linux") {
      this.finder = new LinuxTerminalFinder();
    } else if (this.platform === "darwin") {
      this.finder = new MacTerminalFinder();
    } else {
      this.finder = null;
    }
    if ((deps == null ? void 0 : deps.launch) !== void 0) {
      this.launcher = deps.launch;
    } else if (this.platform === "win32") {
      this.launcher = (term, dir) => {
        var _a2, _b;
        const verified = {
          path: term.binaryPath,
          majorVersion: (_b = (_a2 = term.extra) == null ? void 0 : _a2.majorVersion) != null ? _b : 7
        };
        return launchInteractive(verified, dir);
      };
    } else if (this.platform === "linux") {
      this.launcher = (term, dir) => launchLinuxTerminal(term, dir);
    } else if (this.platform === "darwin") {
      this.launcher = (term, dir) => launchMacTerminal(term, dir);
    } else {
      this.launcher = null;
    }
  }
  isPlatformSupported() {
    return this.platform === "win32" || this.platform === "linux" || this.platform === "darwin";
  }
  getMenuTitle() {
    return "Open Terminal here";
  }
  getRibbonTooltip() {
    return "Open Terminal at vault root";
  }
  setPreferredTerminal(id) {
    var _a, _b;
    this.explicitPreferredTerminal = id;
    (_b = (_a = this.finder) == null ? void 0 : _a.setPreferredTerminal) == null ? void 0 : _b.call(_a, id);
  }
  detectPreferredTerminalFromDom() {
    if (this.explicitPreferredTerminal !== null) {
      return this.explicitPreferredTerminal;
    }
    if (typeof document === "undefined") {
      return null;
    }
    const classList = document.body.classList;
    for (const cls of Array.from(classList)) {
      if (cls.startsWith("terminal-choice-") && cls !== "terminal-choice-auto") {
        return cls.replace("terminal-choice-", "");
      }
    }
    return null;
  }
  async launch(targetDir, preferredTerminal) {
    var _a, _b;
    if (!this.isPlatformSupported() || this.finder === null || this.launcher === null) {
      return { kind: "unsupported_platform", platform: this.platform };
    }
    if (targetDir === null) {
      return { kind: "no_target_path" };
    }
    if (this.platform === "win32" && targetDir.includes(";")) {
      return { kind: "semicolon_in_path" };
    }
    const preferred = preferredTerminal != null ? preferredTerminal : this.detectPreferredTerminalFromDom();
    (_b = (_a = this.finder).setPreferredTerminal) == null ? void 0 : _b.call(_a, preferred);
    let verified = await this.finder.resolve();
    for (let attempt = 0; attempt < MAX_LAUNCH_ATTEMPTS; attempt++) {
      if (verified === null) {
        return { kind: "not_found", platform: this.platform };
      }
      const outcome = await this.launcher(verified, targetDir);
      if (outcome.ok) {
        return { kind: "success" };
      }
      if (outcome.code !== "ENOENT") {
        return { kind: "failed", error: outcome.error };
      }
      if (this.finder.reject !== void 0) {
        this.finder.reject(verified);
      } else if (attempt === 0) {
        this.finder.invalidate();
      } else {
        return { kind: "failed", error: outcome.error };
      }
      verified = await this.finder.resolve();
    }
    return { kind: "not_found", platform: this.platform };
  }
};

// src/main.ts
var RIBBON_ICON = "terminal";
var HIDE_RIBBON_BODY_CLASSES = [
  "hide-vault-terminal-ribbon",
  "hide-vault-powershell-ribbon"
];
var MENU_ITEM_ICON = "terminal";
var NOTICE_UNSUPPORTED_PLATFORM = "Native Terminal Here currently supports Windows, Linux, and macOS.";
var NOTICE_NO_VAULT_PATH = "Unable to resolve the local vault path.";
var NOTICE_NOT_FOUND_WINDOWS = "PowerShell 7 or later was not found. Install PowerShell and restart Obsidian.";
var NOTICE_NOT_FOUND_LINUX = "No supported terminal emulator was found. See the plugin README for the list of supported terminals.";
var NOTICE_NOT_FOUND_MACOS = "No supported terminal app was found. Terminal.app, Ghostty, and Kitty are supported.";
var NOTICE_START_FAILED = "Terminal could not be started. Check the developer console for details.";
var NOTICE_SEMICOLON = "PowerShell cannot be opened for paths containing a semicolon (;).";
var NOTICE_NOT_FOUND = {
  win32: NOTICE_NOT_FOUND_WINDOWS,
  linux: NOTICE_NOT_FOUND_LINUX,
  darwin: NOTICE_NOT_FOUND_MACOS
};
var VaultTerminalPlugin = class extends import_obsidian2.Plugin {
  constructor(app, manifest, deps) {
    var _a, _b;
    super(app, manifest);
    this.ribbonEl = null;
    this.ribbonObserver = null;
    /**
     * Context-menu handler for folders and files.
     * - Shows for a single TFolder (opens that folder).
     * - Shows for a single TFile (opens that file's parent folder).
     */
    this.onFileMenu = (menu, file) => {
      if (!this.terminalManager.isPlatformSupported()) {
        return;
      }
      if (!(file instanceof import_obsidian2.TFolder || file instanceof import_obsidian2.TFile)) {
        return;
      }
      if (!(this.app.vault.adapter instanceof import_obsidian2.FileSystemAdapter)) {
        return;
      }
      const title = this.terminalManager.getMenuTitle();
      menu.addItem((item) => {
        item.setTitle(title).setIcon(MENU_ITEM_ICON).onClick(() => {
          void this.openTerminal(getTargetPath(this.app.vault, file));
        });
      });
    };
    if ((deps == null ? void 0 : deps.terminalManager) !== void 0) {
      this.terminalManager = deps.terminalManager;
    } else {
      const platform = (_b = deps == null ? void 0 : deps.platform) != null ? _b : (_a = deps == null ? void 0 : deps.managerDeps) == null ? void 0 : _a.platform;
      this.terminalManager = new TerminalManager({
        platform,
        ...deps == null ? void 0 : deps.managerDeps
      });
    }
  }
  onload() {
    const tooltip = this.terminalManager.getRibbonTooltip();
    const ribbonEl = this.addRibbonIcon(RIBBON_ICON, tooltip, () => {
      void this.openTerminal(getVaultRootPath(this.app.vault));
    });
    ribbonEl.addClass("vault-terminal-ribbon");
    ribbonEl.addClass("vault-powershell-ribbon");
    this.ribbonEl = ribbonEl;
    this.setupRibbonVisibilityEnforcement();
    this.registerEvent(this.app.workspace.on("file-menu", this.onFileMenu));
  }
  onunload() {
    var _a;
    (_a = this.ribbonObserver) == null ? void 0 : _a.disconnect();
    this.ribbonObserver = null;
    this.ribbonEl = null;
    super.onunload();
  }
  /**
   * Enforce the Style Settings hide toggle in JS via MutationObserver.
   */
  setupRibbonVisibilityEnforcement() {
    if (typeof document === "undefined" || typeof MutationObserver === "undefined") {
      return;
    }
    const apply = () => {
      if (this.ribbonEl === null) {
        return;
      }
      const shouldHide = HIDE_RIBBON_BODY_CLASSES.some(
        (cls) => document.body.classList.contains(cls)
      );
      this.ribbonEl.style.display = shouldHide ? "none" : "";
    };
    this.ribbonObserver = new MutationObserver(apply);
    this.ribbonObserver.observe(document.body, {
      attributes: true,
      attributeFilter: ["class"]
    });
    apply();
  }
  /**
   * Open the native terminal at the given target directory.
   */
  async openTerminal(targetDir) {
    var _a;
    const result = await this.terminalManager.launch(targetDir);
    switch (result.kind) {
      case "success":
        return;
      case "unsupported_platform":
        new import_obsidian2.Notice(NOTICE_UNSUPPORTED_PLATFORM);
        return;
      case "no_target_path":
        new import_obsidian2.Notice(NOTICE_NO_VAULT_PATH);
        return;
      case "semicolon_in_path":
        new import_obsidian2.Notice(NOTICE_SEMICOLON);
        return;
      case "not_found":
        new import_obsidian2.Notice((_a = NOTICE_NOT_FOUND[result.platform]) != null ? _a : NOTICE_NOT_FOUND_LINUX);
        return;
      case "failed":
        console.error("[Native Terminal Here] launch failed", result.error);
        new import_obsidian2.Notice(NOTICE_START_FAILED);
        return;
    }
  }
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  NOTICE_NOT_FOUND_LINUX,
  NOTICE_NOT_FOUND_MACOS,
  NOTICE_NOT_FOUND_WINDOWS,
  NOTICE_NO_VAULT_PATH,
  NOTICE_SEMICOLON,
  NOTICE_START_FAILED,
  NOTICE_UNSUPPORTED_PLATFORM
});
